name: Run CI/CD for PageKey Semver package.

on:
  push:
    tags: ["*"]
    branches: ["*"]

jobs:
  version:
    uses: ./.github/workflows/semver.yml
    secrets:
      SEMVER_USER: ${{ secrets.SEMVER_USER }}
      SEMVER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install poetry
        run: pip3 install poetry

      - name: Install with dev deps
        run: poetry install --with dev

      - name: Run tests
        run: poetry run pytest

  publish2:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Placeholder
        env:
          SEMVER_NEW_RELEASE: ${{ needs.version.outputs.semver_new_release }}
        run: |
          echo release var is $SEMVER_NEW_RELEASE
          echo '${{ toJSON(needs.job1.outputs) }}'

  publish:
    runs-on: ubuntu-latest
    needs: version
    if: ${{ needs.version.outputs.semver_new_release == 'true' }}
    steps:
      - name: Placeholder
        run: echo Coming soon.
