name: Run CI/CD for PageKey Semver package.

on: [push]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install ruff
        run: pip3 install ruff

      - name: Check for ruff format failures
        run: ruff format . --check

      - name: Check for ruff failures
        run: ruff check .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install poetry
        run: pip3 install poetry

      - name: Install with dev deps
        run: poetry install --with dev

      - name: Run tests
        run: poetry run pytest

  version:
    needs: [lint, test]
    uses: ./.github/workflows/semver.yml
    secrets:
      SEMVER_USER: ${{ secrets.SEMVER_USER }}
      SEMVER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs: version
    if: ${{ needs.version.outputs.semver_release_occurred == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch all commits instead of just current one
      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          git pull
          pip install poetry
          poetry install --with dev
          poetry publish --build --username __token__ --password $PYPI_TOKEN

  mirror:
    runs-on: ubuntu-latest
    needs: [lint, test, version]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch all commits instead of just current one
      - name: Create remote and push
        env:
          GITLAB_USER: ${{ secrets.GITLAB_USER }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://$GITLAB_USER:$GITLAB_TOKEN@gitlab.com/pagekey/semver.git
          git remote remove origin
          git push --mirror gitlab
