name: PageKey Semver

on:
  # This key makes it reusable.
  workflow_call:
    inputs:
      SEMVER_TOKEN:
        description: 'The token used to authenticate when pushing Git.'
        required: true
        type: secret

jobs:
  run-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch all commits instead of just current one

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install semver
        run: pip3 install pagekey-semver

      - name: Run semver live when on main
        if: github.ref == 'refs/heads/main'
        run: pagekey-semver apply

      - name: Run semver dry-run when not on main
        if: github.ref != 'refs/heads/main'
        run: pagekey-semver plan
