name: PageKey Semver

on:
  # This key makes it reusable.
  workflow_call:
    secrets:
      SEMVER_USER:
        description: 'The usernae used to authenticate when pushing Git.'
        required: true
      SEMVER_TOKEN:
        description: 'The token used to authenticate when pushing Git.'
        required: true

jobs:
  run-release:
    outputs:
      semver_new_release: ${{ steps.apply.outputs.SEMVER_NEW_RELEASE }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch all commits instead of just current one

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install semver
        # run: pip3 install pagekey-semver # TODO uncomment
        run: pip3 install . # TODO remove

      - name: Run semver live when on main
        if: github.ref == 'refs/heads/main'
        run: pagekey-semver apply
        id: apply

      - name: Run semver dry-run when not on main
        if: github.ref != 'refs/heads/main'
        run: pagekey-semver plan
